title: The Green Book
description: A guide by Eric Rogler on the art of communication, teaching, and instruction. 
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

search_enabled: false

# External navigation links
nav_external_links:
    hide_icon: false # set to true to hide the external link icon - defaults to false
    opens_in_new_tab: true # set to true to open this link in a new tab - defaults to false